import type { InboxFolder, InboxThread } from './types';

export const mockFolders: InboxFolder[] = [
  { id: 'folder-1', name: 'VIP Guests', color: '#f59e0b', parentId: null, order: 0 },
  { id: 'folder-2', name: 'Pending Bookings', color: '#3b82f6', parentId: null, order: 1 },
  { id: 'folder-3', name: 'Support', color: '#ef4444', parentId: null, order: 2 },
  { id: 'folder-4', name: 'Vendors', color: '#22c55e', parentId: null, order: 3 },
  { id: 'folder-5', name: 'Chefs', color: '#8b5cf6', parentId: 'folder-4', order: 0 },
  { id: 'folder-6', name: 'Cleaners', color: '#06b6d4', parentId: 'folder-4', order: 1 },
];

export const mockThreads: InboxThread[] = [
  {
    id: 'thread-1',
    senderName: 'Sarah Johnson',
    senderAvatar: undefined,
    subject: 'Question about early check-in',
    snippet: 'Hi! I was wondering if we could possibly check in a bit earlier than 3pm? Our flight arrives at...',
    folderId: 'folder-1',
    platform: 'gmail',
    isStarred: true,
    isRead: false,
    timestamp: new Date('2025-01-27T16:30:00'),
    messages: [
      {
        id: 'msg-1-1',
        from: 'Sarah Johnson',
        content: 'Hi! I was wondering if we could possibly check in a bit earlier than 3pm? Our flight arrives at 11am and we\'d love to drop off our bags if possible.',
        timestamp: new Date('2025-01-27T14:00:00'),
        isOutgoing: false,
      },
      {
        id: 'msg-1-2',
        from: 'You',
        content: 'Hi Sarah! Thank you for reaching out. I\'ll check with our cleaning team and get back to you shortly.',
        timestamp: new Date('2025-01-27T15:30:00'),
        isOutgoing: true,
      },
      {
        id: 'msg-1-3',
        from: 'Sarah Johnson',
        content: 'Thank you so much! We really appreciate your help.',
        timestamp: new Date('2025-01-27T16:30:00'),
        isOutgoing: false,
      },
    ],
  },
  {
    id: 'thread-2',
    senderName: 'Michael Chen',
    senderAvatar: undefined,
    subject: 'WiFi password not working',
    snippet: 'The WiFi password in the welcome guide doesn\'t seem to be working. Could you please send the correct...',
    folderId: 'folder-3',
    platform: 'whatsapp',
    isStarred: false,
    isRead: false,
    timestamp: new Date('2025-01-27T14:15:00'),
    messages: [
      {
        id: 'msg-2-1',
        from: 'Michael Chen',
        content: 'The WiFi password in the welcome guide doesn\'t seem to be working. Could you please send the correct one?',
        timestamp: new Date('2025-01-27T14:15:00'),
        isOutgoing: false,
      },
    ],
  },
  {
    id: 'thread-3',
    senderName: 'Premium Clean Co.',
    senderAvatar: undefined,
    subject: 'Re: Cleaning schedule update',
    snippet: 'We\'ve confirmed the schedule for next week. All properties are covered as requested.',
    folderId: 'folder-6',
    platform: 'gmail',
    isStarred: false,
    isRead: true,
    timestamp: new Date('2025-01-27T10:00:00'),
    messages: [
      {
        id: 'msg-3-1',
        from: 'You',
        content: 'Hi team, can you confirm the cleaning schedule for next week?',
        timestamp: new Date('2025-01-26T16:00:00'),
        isOutgoing: true,
      },
      {
        id: 'msg-3-2',
        from: 'Premium Clean Co.',
        content: 'We\'ve confirmed the schedule for next week. All properties are covered as requested.',
        timestamp: new Date('2025-01-27T10:00:00'),
        isOutgoing: false,
      },
    ],
  },
  {
    id: 'thread-4',
    senderName: 'Emily Rodriguez',
    senderAvatar: undefined,
    subject: 'Reservation confirmation',
    snippet: 'Thank you for confirming our reservation! We\'re so excited for our trip. Quick question about...',
    folderId: 'folder-2',
    platform: 'facebook',
    isStarred: true,
    isRead: true,
    timestamp: new Date('2025-01-26T18:45:00'),
    messages: [
      {
        id: 'msg-4-1',
        from: 'Emily Rodriguez',
        content: 'Thank you for confirming our reservation! We\'re so excited for our trip. Quick question about parking - is there a dedicated spot for guests?',
        timestamp: new Date('2025-01-26T18:45:00'),
        isOutgoing: false,
      },
    ],
  },
  {
    id: 'thread-5',
    senderName: 'Chef Michael Laurent',
    senderAvatar: undefined,
    subject: 'Menu options for upcoming service',
    snippet: 'Here are the menu options for the private dinner next Saturday. Please let me know which works...',
    folderId: 'folder-5',
    platform: 'whatsapp',
    isStarred: false,
    isRead: true,
    timestamp: new Date('2025-01-25T11:20:00'),
    messages: [
      {
        id: 'msg-5-1',
        from: 'Chef Michael Laurent',
        content: 'Here are the menu options for the private dinner next Saturday. Please let me know which works best for the guests:\n\n1. Mediterranean Feast\n2. Modern American\n3. Italian Classic',
        timestamp: new Date('2025-01-25T11:20:00'),
        isOutgoing: false,
      },
    ],
  },
  {
    id: 'thread-6',
    senderName: 'David Lee',
    senderAvatar: undefined,
    subject: 'Late checkout request',
    snippet: 'Would it be possible to checkout at 2pm instead of 11am?',
    folderId: null,
    platform: 'instagram',
    isStarred: false,
    isRead: false,
    timestamp: new Date('2025-01-25T09:00:00'),
    messages: [
      {
        id: 'msg-6-1',
        from: 'David Lee',
        content: 'Would it be possible to checkout at 2pm instead of 11am?',
        timestamp: new Date('2025-01-25T09:00:00'),
        isOutgoing: false,
      },
    ],
  },
];
